# Generated by Django 4.1.5 on 2023-01-27 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('leave_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='co_travellers',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='co_travelers',
            field=models.ManyToManyField(blank=True, related_name='itineraries_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='plan',
            field=models.ManyToManyField(to='itinerary.agenda'),
        ),
    ]
