# Generated by Django 4.1.5 on 2023-02-04 10:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('phone_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('fax_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_child', models.FloatField()),
                ('thai_adult', models.FloatField()),
                ('foreigner_child', models.FloatField()),
                ('foreigner_adult', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sub_district', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('introduction', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('category_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('bd_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha_name', models.CharField(max_length=255)),
                ('sha_type_code', models.CharField(max_length=255)),
                ('sha_type_description', models.CharField(max_length=255)),
                ('sha_cate_id', models.CharField(max_length=255)),
                ('sha_cate_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('hotel_star', models.CharField(max_length=255)),
                ('register_license_id', models.CharField(max_length=255)),
                ('display_checkin_time', models.TimeField()),
                ('number_of_rooms', models.IntegerField()),
                ('price_range', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('hit_score', models.CharField(max_length=255)),
                ('accomodation_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('accomodation_rooms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
            bases=('places.place',),
        ),
        migrations.AddField(
            model_name='place',
            name='sha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.sha'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('standard', models.CharField(max_length=255)),
                ('shop_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('opening_hours', models.ManyToManyField(related_name='shop_opening_hours', to='places.openinghour')),
            ],
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('standard', models.CharField(max_length=255)),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('hit_score', models.CharField(max_length=255)),
                ('restaurant_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('cuisine_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('michelines', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('opening_hours', models.ManyToManyField(related_name='restaurant_opening_hours', to='places.openinghour')),
            ],
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('hit_score', models.CharField(max_length=255)),
                ('attraction_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.fee')),
                ('opening_hours', models.ManyToManyField(related_name='attraction_opening_hours', to='places.openinghour')),
            ],
            bases=('places.place',),
        ),
    ]
