# Generated by Django 4.1.5 on 2023-02-25 04:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='how_to_travels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='mobile_picture_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='web_picture_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.accommodation'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accomodation_rooms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accomodation_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='awards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_fee', to='places.fee'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='foreigner_adult',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='foreigner_child',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='thai_adult',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='thai_child',
            field=models.FloatField(default=0),
        ),
    ]
